### ISSUE TITLE
Unexpected "受付終了" label for homework-tasks which isn't set deadline

### ISSUE THREAD

**Issue by asagatto777** [mkobayashime/manaba-enhanced#1]
If deadline isn't set for homework-tasks, unexpected "受付終了" label appear.
![image](https://user-images.githubusercontent.com/17997951/84635049-a4b5fa00-af2d-11ea-8f69-d92c85fefe33.png)

**Comment by mkobayashime** [comment]
@asagatto777 Thanks for the reporting.
16fc5af5568f48843c0d6d897521c72356da3d79 should have fixed this.
