### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by mkobayashime** [mkobayashime/manaba-enhanced#12]

**Comment by mkobayashime** [comment]
Firefox support is done in implementation level, but the way to distribute is the trouble. Publishing this extension to AMO (addons.mozilla.org) has rejected as it can be used by _limited/non-public audiece_, and they suggested self distribution which is really complicated.

**Comment by onokatio** [comment]
@mkobayashime How about distributing as Github Release?
Firefox can also install extensions from outside the store

**Comment by onokatio** [comment]
Of course, it is not kind, but it is better than not distributing it.
