### ISSUE TITLE
ファイルダウンロードのフォルダ分け

### ISSUE THREAD

**Issue by smasato** [mkobayashime/manaba-enhanced#139]
manaba上でダウンロードしたファイルを科目毎にフォルダ分けされると便利な気がします。
「線形代数A」であれば `~/Downloads/線形代数A/` に保存されるようなイメージです。
Chrome拡張で実現できるかはわかりませんが検討してみてください。

**Comment by mkobayashime** [comment]
ご提案ありがとうございます

単一のあるファイルがダウンロードされる際のダウンロード先ディレクトリに関しては Chrome 拡張やページ側から干渉する術が一切ありませんので、基本的には実装はできません
「履修している全科目の公開ファイルを一括で zip としてダウンロードする」機能の一環として科目ごとのフォルダ分け(zip 内での)を実装することは可能かと思われますが、以下の理由から現状私が実装することは検討しておりません

- この機能の実現のためにはダウンロードのタイミングで manaba 上の各科目のページを手当り次第クロールして公開されているファイルを探すような処理がどうしても必要になり、サービスの適正な利用の範疇と言えるか自信が持てないこと(このため現状 manaba Enhanced には「そのとき見えているページ内容からわかる」情報以外が必要な機能を実装していません)
- 私自身特に当該機能の必要性を感じていないこと

というわけで一旦 won't fix として close させていただきますが、上記の問題点を解決して実装してくださる方がいればコントリビュートは歓迎という形にさせていただきます
なおこちらの中央大学向けの Chrome 拡張ではこのファイルの一括ダウンロード機能が実装されているようですので、実装にあたり参考になるかもしれません
https://github.com/kajikentaro/manaba-plus
