### ISSUE TITLE
Test framework

### ISSUE THREAD

**Issue by yudukikun5120** [mkobayashime/manaba-enhanced#419]
We need to introduce a unit test framework (e.g. Jest) to continue the development. Do you have any plans for the test suite?

**Comment by mkobayashime** [comment]
Thanks for the suggestion!
I'm not opposed to introduction of tests, but I'm afraid not so many codes are testable because they depend on the page structure of original manaba heavily (and doing e2e isn't realistic as well considering authentication on CI), that's why I haven't been written tests in this repo. Though I think simple unit tests could still be done in some parts, so I'll be happy doing that if there's some case which is testable in simple unit tests and is complex to some extent (needs testing). Do you have some?

**Comment by yudukikun5120** [comment]
Exactly, I came across a situation that needs a unit test.
I wrote a function named `injectReportInfoIntoRawText`.

```TypeScript
const injectReportInfoIntoRawText = (
    rawText: string,
    reportInfo: ReturnType<typeof this.searchReportInfo>
  ) =>
    Object.entries(reportInfo).reduce(
      (acc, [key, value]) =>
        acc.replaceAll(
          `{{${key}}}`,
          typeof value === "string" ? value : value.toLocaleString()
        ),
      rawText
    )
```

This function intends to convert the string from `The report whose title is {{report-title}} is due to {{deadline}}` to `The report whose title is The Great Report is due to 2021/1/1 0:00:00`.
I also wrote the test code in Jest:

```TypeScript
  test("replace expressions with report info", () => {
    const reportInfo = {
      courseName: `The Great Course`,
      reportTitle: `The Great Report`,
      studentName: `Tsukuba Taro`,
      deadline: new Date(`2021-01-01 00:00:00`),
      description: `Show how great the university of Tsukuba is.`,
    }
    const userTemplate = `The report whose title is {{report-title}} is due to {{deadline}}`
    const expectedUserTemplate = `The report whose title is The Great Report is due to 2021/1/1 0:00:00`

    expect(injectReportInfoIntoRawText(userTemplate, reportInfo)).toBe(expectedUserTemplate)
```

The test assures the function `injectReportInfoIntoRawText` truly works although it is a little bit complex and takes some attention.
In addition, the test code could clear the intentions of the functions or class methods more than JSDoc (of course, JSDoc is necessary to stand the behaviors of the function).

I would like to open the pull request to introduce Jest to this project if you’re ok.

Thanks.

**Comment by mkobayashime** [comment]
@yudukikun5120 
I understood your need. Could you please open a PR to introduce Jest?
As for Jest with TypeScript my personal preference is `@swc/jest` because of its performance advantage over `ts-jest` (and we don't need type cheking duplicated with `tsc --noEmit` in test process), lets discuss here if you prefer another one.
Thanks.

**Comment by yudukikun5120** [comment]
@mkobayashime I'd like to know which the task `yarn run test` should be written, in the Makefile or in npm scripts. I think the npm scripts could be better for the integration with Visual Studio Codes. Let me know the advantages of using Makefile as a task building tool.

**Comment by mkobayashime** [comment]
@yudukikun5120 
In general I prefer Makefile, but we can use yarn scripts if it's reasonable.
Could you please explain what you mean in better integration with VSCode as I don't use VSCode regularly? If you are to use [Orta.vscode-jest](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest), it seems the extension works without any special settings (regardless of the task runner we use) by finding the Jest binary from `node_modules` automatically (I confirmed this in my [another project](https://github.com/mkobayashime/t7s-songs) where test results are correctly displayed next to the line numbers).

BTW the reasons I use Makefile are:
- easy to specify dependency of tasks (like `node_modules` target in this repo, without something like `npm-run-all`, and in reasonable format unlike `npm-run-all`).
- task names can be Tab auto-completed (`$ make type[Tab]` → `$make typecheck`) in zsh, which is very handy for me.

I personally would like to run tasks with make uniformly, so it'll be nice to have make target like below if you use yarn scripts.

```make
test: node_modules
	yarn run test
```

**Comment by yudukikun5120** [comment]
@mkobayashime 

Thank you for noticing me about the advantages of Makefile and the VSCode extension for Jest.

I can say NPM scripts also have the advantages in VSCode:

1. [Auto task detection](https://code.visualstudio.com/Docs/editor/tasks#_task-autodetection). Gulp, Grunt, Jake, and npm are supported systems.
2. [Run npm scripts as tasks from the Explorer](https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_run-npm-scripts-as-tasks-from-the-explorer). Run NPM scripts from the explorer panel with ease.

Makefile would be brilliant when you needed to consider task concurrency or a certain task depending on something that you needed to bother to denote (in that context, the tasks which performed in the NodeJS project ordinarily use and depend on `node_modules`).

Therefore, I'd like to write the task in the NPM scripts (`package.json`) and wrap it in Makefile.

**Comment by yudukikun5120** [comment]
@mkobayashime I did it. Could you review this PR?

**Comment by mkobayashime** [comment]
@yudukikun5120 
I understood the situation with VSCode well, and would love to respect your decision!
