### ISSUE TITLE
Create `.node-version` file to specify the node version to use.

### ISSUE THREAD

**Issue by yudukikun5120** [mkobayashime/manaba-enhanced#439]
This is useful if you are using nvm or nodenv to manage node versions.
    
- [ ] Create `.node-version`

But I do not know which version of node to use. CI is using 18, but it would be preferable to know the exact version to use like 18.1.1.

### Refs
- https://github.com/nodenv/nodenv#choosing-the-node-version

**Comment by mkobayashime** [comment]
It's apparently nice to have one, but specifying concrete version (includes minor/patch version) is the way too much IMO. Installing the specified version just for this repo is a mess, forcing a major version should be OK for such project.
By the way I assume the file format should be `.nvmrc` as nvm has much larger popularity over nodenv according to [Google Trends](https://trends.google.com/trends/explore?geo=JP&q=nvm,nodenv) (I personally use nodenv with [nodenv-nvmrc](https://github.com/ouchxp/nodenv-nvmrc) which makes nodenv respect `.nvmrc`).

**Comment by yudukikun5120** [comment]
@mkobayashime Thank you for introducing me _nodenv-nvmrc_, which seems to be fine. I agree with the decision that the minimum specification of the Node version and it'll be fine.
