### ISSUE TITLE
Add Code Climate badge to `README.md` to show code quality

### ISSUE THREAD

**Issue by yudukikun5120** [mkobayashime/manaba-enhanced#443]
Code Climate is a service that analyzes code to detect code smells, bugs, and security vulnerabilities. It also provides automated code review comments.
This issue proposes adding a badge to the `README.md` to show the current code quality of the project as an OSS project. Also, we can use it for free for OSS projects.
I'm afraid to say that collaborators of this repo cannot add it to Code Climate[^1]. So could you do it? I think it's easy to do. Just follow the instruction[^2] and add this repo to Code Climate. Then you can get a badge markdown and add it to `README.md`.

Of course, you can reject this proposal if you don't want to use Code Climate. I'm just suggesting it because I think it's useful for OSS projects.

[^1]: https://docs.codeclimate.com/docs/open-source-free#administering-open-source-repositories
[^2]: https://docs.codeclimate.com/docs

**Comment by mkobayashime** [comment]
Why not!

**Comment by yudukikun5120** [comment]
@mkobayashime Sorry for my misunderstanding, there might not be a team feature for Code Climate.

**Comment by mkobayashime** [comment]
It's OK, and I think issues are public (can be accessed by anyone).

**Comment by mkobayashime** [comment]
GItHub issues integration could works, but it seems a little bit troublesome as it needs my GitHub personal access token (expires and needs updating regularly). Could you please see issues in the Code climante page (from the badge) for now?

**Comment by yudukikun5120** [comment]
@mkobayashime I can see issues on the Code Climate page! I'm really sorry to you because of taking time for my ignorance.

**Comment by mkobayashime** [comment]
@yudukikun5120 No problem!
