### ISSUE TITLE
Upgrade Manifest to V3

### ISSUE THREAD

**Issue by yudukikun5120** [mkobayashime/manaba-enhanced#457]
## Motivation
The current manifest format is not extensible. We need to upgrade it to v3.

### Refactoring
Manifest V3 includes `Promise` support, which is critical for the `Chrome.Storage` API. In V2, it causes the callback hell.

`Chrome.Storage` API is playing a critical role in the extension. We could rewrite the storage API to use `async/await`. It will make the code more readable.

We need to upgrade to V3 as soon as possible.

## References
- https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/

**Comment by mkobayashime** [comment]
We are waiting for the official support of MV3 in Firefox. (see #8)

**Comment by mkobayashime** [comment]
We can discuss in the original issue (#8).
